### ISSUE TITLE
Black icon in tray at boot

### ISSUE THREAD

**Issue by phdzor** [yktoo/indicator-sound-switcher#91]
When i boot into my Arch Linux icon in tray is black but when i right click - Quit the app and manually start it icon is normal color:

![image](https://i.imgur.com/05xQsvN.png)
![Image](https://i.imgur.com/V4OZY5U.png)

**Comment by yktoo** [comment]
I can't really come up with any possible explanation except for that it's a bug in Arch Linux or the Ayatana/AppIndicator lib.

**Comment by emersonrp** [comment]
I'm having the same trouble, except quitting and restarting manually it still comes up black.  This is with Manjaro Linux, which is Arch-adjacent, so might indeed be a bug in Arch.  Will update if I figure anything out.

**Comment by fabrizziosoares** [comment]
In my case, I have no icon at all. The indicator looks like an empty space, it responds to my commands, but no icon is shown. I am using Linux Mint 20. It was OK until something updated. I tried to reboot; manually start, but nothing changed. I also started it with -vv option to see if some error show up in verbose mode, but I found nothing. I don't know if it is a bug in Cinamon theme, or if I broke something after installing. Is there any package I should reinstall to see if it fixes the problem?

**Comment by yktoo** [comment]
@fabrizziosoares Did you try to refresh icon cache as suggested [here](https://github.com/yktoo/indicator-sound-switcher/issues/90#issuecomment-649461820)?

**Comment by fabrizziosoares** [comment]
Dear @yktoo I didn't try yet. Now I did and I still have the same problem. On important detail is that the icon appears on about box. It does not appear only on the tray.

**Comment by fabrizziosoares** [comment]
That's precisely the problem I am having. It looks like it happened after some update, but I don't know which one.

**Comment by evert-mouw** [comment]
I only get the black icon. It would be nice if a preference setting could override it. I'm on an updated Arch Linux with indicator-sound-switcher-2.3.4

(Using sound switch a lot -- thanks for creating and maintaining it!!!)

**Comment by gnutix** [comment]
Same issue here on Pop!_OS with Cinnamon, no icon in the system tray. :(

**Comment by yktoo** [comment]
I'm afraid these reports do not bring us any closer to the solution. 

What I suspect is happening is that different distros / DEs handle icons a bit differently, which is further diversified by the use of themes.

I would recommend playing around with the icon files by copying them to various locations under `/usr/share/icons/`. Perhaps the problem is the SVG format so you might also try to fall back to using PNG.

Important: do not forget to refresh the icon cache after copying, otherwise the changes won't be detected by the system:

```bash
sudo update-icon-caches /usr/share/icons/*
```

**Comment by yktoo** [comment]
Closing until more information is available.

**Comment by Frost4142** [comment]
There is no icon in the system tray

OS Ubuntu Studio
kernel 5.11.0-41-low latency
XFCE
Sound Switcher Indicator version 2.3.6

Sound Switcher Indicator is installed via the repository
The program is working. There is only an icon in the tray. More precisely, an empty space where the icon should be. I changed the icon themes without result. Maybe we need to put svg somewhere so that the program can see them?

**Comment by yktoo** [comment]
@Frost4142 try to move icons around as suggested above:

> What I suspect is happening is that different distros / DEs handle icons a bit differently, which is further diversified by the use of themes.
> 
> I would recommend playing around with the icon files by copying them to various locations under `/usr/share/icons/`. Perhaps the problem is the SVG format so you might also try to fall back to using PNG.
> 
> Important: do not forget to refresh the icon cache after copying, otherwise the changes won't be detected by the system:
> 
> ```shell
> sudo update-icon-caches /usr/share/icons/*
> ```

**Comment by Frost4142** [comment]
I have tried all of the above methods with no result. When you start the program manually, the tray icon appears for a second and disappears.

**Comment by yktoo** [comment]
@Frost4142  cannot reproduce it. Here's a vanilla Xubuntu 21.10 install:
![image](https://user-images.githubusercontent.com/1675911/143464650-a8436b92-fad6-4816-81be-4902fac02a17.png)

**Comment by Frost4142** [comment]
https://disk.yandex.ru/d/wjntPcpO6MsQIg

**Comment by Frost4142** [comment]
https://disk.yandex.ru/d/78dl0BzdYME-YQ

**Comment by Frost4142** [comment]
https://disk.yandex.ru/i/u6FiYKPBQKy59g

**Comment by Frost4142** [comment]
https://disk.yandex.ru/d/rQ9RnVrGxdVudQ

**Comment by Frost4142** [comment]
I solved the problem by installing the old version
indicator-sound-switcher_2.2.2-1_all.deb

**Comment by yktoo** [comment]
Screenshots are good but I need to reproduce the problem in order to diagnose it. So far I failed to find a combination of OS and DE that would reproduce this behaviour.

**Comment by yktoo** [comment]
If I compare the latest version to 2.2.2, here are the differences in copied icons:

```diff
-    ('share/icons/ubuntu-mono-dark/status/22',  ['icons/ubuntu-mono-dark/indicator-sound-switcher.svg']),
-    ('share/icons/ubuntu-mono-light/status/22', ['icons/ubuntu-mono-light/indicator-sound-switcher.svg']),
-    ('share/icons/hicolor/22x22/status',        ['icons/default/indicator-sound-switcher.svg']),
-    ('share/icons/hicolor/scalable/status',     ['icons/default/indicator-sound-switcher.svg']),
+    ('share/icons/hicolor/scalable/status',     ['icons/indicator-sound-switcher-symbolic.svg']),
+    ('share/icons/hicolor/scalable/apps',       ['icons/indicator-sound-switcher.svg']),
```

This could give you a hint which locations do work for you and which don't.

**Comment by Frost4142** [comment]
I will experiment more ! I will write how the result will be ! But it also works well with the old version )
https://yadi.sk/d/Mu7uv6DtU2EmOw
https://yadi.sk/d/mIvNUPSJFzTJvw

**Comment by Frost4142** [comment]
It seems to me that the problem is in the Ubuntu Studio distribution I installed indicator-sound-switcher
in Mint 20.2 there
were no problems

**Comment by yktoo** [comment]
I still can't reproduce it, using Ubuntu Studio 21.10. The icon appears OK in both KDE and XFCE sessions.
![image](https://user-images.githubusercontent.com/1675911/143556901-66f027ca-3969-4373-a54b-66e4b9f0d883.png)

**Comment by Frost4142** [comment]
xfce+compiz+emerald
maybe because of this ?

**Comment by Frost4142** [comment]
https://disk.yandex.ru/d/Wa7IfPE9zEfnOQ

**Comment by Frost4142** [comment]
Won !
Posted a png here
/usr/share/icons/hicolor/symbolic/apps/indicator-sound-switcher.png
/usr/share/icons/hicolor/symbolic/apps/indicator-sound-switcher-symbolic.png

**Comment by yktoo** [comment]
Looks good, I see that in stock Ubuntu symbolic icons are somewhat scattered between `/usr/share/icons/hicolor/scalable/` and `/usr/share/icons/hicolor/symbolic/`.

The icon is totally black though, I wonder if it looks better if you only put an SVG icon into `/usr/share/icons/hicolor/symbolic/apps/indicator-sound-switcher-symbolic.svg` (and remove all other icons)?

**Comment by Frost4142** [comment]
Now in detail
The black icon appeared when I turned on the SVG option in the composite manager
in the /image upload section/
I have a similar problem I was with the Crow Translate program
But everything was solved there simply in the settings there is a parameter where you can specify the user icon
I looked at the DEB package where he unpacks his icons
and, by analogy, placed the ISS icons in these directories
, these ones worked paths
/usr/share/icons/hicolor/symbolic/apps/indicator-sound-switcher.png
/usr/share/icons/hicolor/symbolic/apps/indicator-sound-switcher-symbolic.png
after sudo update-icon-caches /usr/share/icons/*
A white icon lit up in the tray

https://yadi.sk/d/AqlqgJOSUq-DjA

**Comment by Frost4142** [comment]
>/usr/share/icons/hicolor/scalable/ and /usr/share/icons/hicolor/symbolic/.
>/usr/share/icons/hicolor/symbolic/apps/indicator-sound-switcher-symbolic.svg (and remove all other icons)?
I tried it the icon remained black

**Comment by yktoo** [comment]
Hmmm it's still not clear to me whether it can handle SVG, or I also need to ship a PNG.

@Frost4142 can you confirm that **with SVG only** (no PNG) the icon is still present?

**Comment by Frost4142** [comment]
The tray icon appeared when turned on in Compiz, but it was invisible
/empty space or transparency I don't know /
PNG worked all the same when I put
it here by these routes

/usr/share/icons/hicolor/symbolic/apps/indicator-sound-switcher.png
/usr/share/icons/hicolor/symbolic/apps/indicator-sound-switcher-symbolic.png

I can also add that somehow there were the same problems with the Viber program
, then I downloaded the Viber installation in /opt, the icon began to display normally
. I remembered about this when I was collecting qmmp, I changed empty_cover there, but what would it display 
it was necessary to reassemble
the ari package to the assembly with the software parameters by default, it not only did not display empty_cover noramally
, but stopped seeing plugins and the program icon also disappeared, I reassembled it in /opt
based on from the aforementioned Viber
, everything worked with a bang
I do not know With what options packages are assembled in the Ubuntu Studio distribution
, but it seems that there is a problem right here 
I will also try to assemble your program and see what happens and I will write to you

**Comment by yktoo** [comment]
I have just pushed version 2.3.7 of the app, with fallback PNG/SVG icons. Please give it a try and report back if the problem persists.

**Comment by Frost4142** [comment]
Ok I will try to install this on a virtual machine for the purity of the experiment. Only a little later, now I'm just not busy with work. End of the year -)

**Comment by Frost4142** [comment]
I still deleted 2.3.6
Cleaned up all the experiments
And installed 2.3.7 
Everything works

https://disk.yandex.ru/i/sdb6q_eW6MhJaQ

**Comment by madhur** [comment]
Same issue here on Cinnamon 4.6.7

**Comment by mxmilkiib** [comment]
Can the app be made to log, in -vv, the path it's getting the icon from? Black on black on Arch. How is the app detecting a dark theme? I'm using Awesome WM. Can a settings menu radio button override be added? Thanks!

**Comment by yktoo** [comment]
@mxmilkiib That'd be helpful indeed. Unfortunately, the app knows nothing of that, it's entirely handled by the GTK and the AppIndicator library. This is how it looks in practice:

```python
self.ind = AppIndicator.Indicator.new(
    APP_ID,
    'indicator-sound-switcher-symbolic', # This is the icon
    AppIndicator.IndicatorCategory.HARDWARE)
```

**Comment by mxmilkiib** [comment]
This isn't fixed in 2.3.8. Can the issue be reopened please?

**Comment by mxmilkiib** [comment]
Can you just, like, please add a flag? :)

**Comment by yktoo** [comment]
Reopened, but I'm not sure what I can do to diagnose that. I still think the icon is searched by the system at a wrong location.

**Comment by mxmilkiib** [comment]
If I change the icon tray bg colour to red in the AwesomeWM theme configuration, it shows a black i-s-s icon, so the path can't be wrong, no? Using qt5ct configuration editor, if I change the icon theme to a non-dark one and apply, [flameshot](https://github.com/flameshot-org/flameshot) changes it's icon within a few seconds. Hmm, what's a good fully GTK based app with a theme respecting icon to test with?

**Comment by yktoo** [comment]
Okay, so the icon is found and rendered, but it isn't the right one for the current theme. The SSI is shipped with [symbolic icons](https://wiki.gnome.org/Design/OS/SymbolicIcons), so perhaps your WM doesn't support these?

**Comment by mxmilkiib** [comment]
There's only one SVG for your app, and it's light coloured. This is very confusing. I'm sure it's just the standard old school XEMBED method, and if there was a problem with with this with the WM, it would have turned up already. However, my and some others configuration could be incorrect; maybe there is a foreground colour variable that is unset, but I try a lot of apps and I can't recall (with my admittedly bad memory) a situation like this previously, and I couldn't see anything directly appropriate when I went down the path of looking for issues with a similar setup with the same problem, but ran out of time yesterday, will get back around to that again at some point

**Comment by mxmilkiib** [comment]
Reading above again; how might I make the app fallback to using png for the tray icon?

**Comment by yktoo** [comment]
@mxmilkiib there's a regular SVG icon (`indicator-sound-switcher.svg`) and a symbolic one (`indicator-sound-switcher-symbolic.svg`), the latter is indeed light but that shouldn't matter as symbolic icons are recoloured by the DE to match the current theme (that's the whole point of using symbolic icons).

There's also a whole bunch of PNGs shipped with the SSI, and my best guess would be they have to be at a certain subdirectory under `/usr/share/icons/` for the DE to pick them up. I'm afraid I cannot provide any more details as I'm not familiar with Awesome WM.

What's also worth keeping in mind is that the icons can be cached, so the changes in the filesystem won't immediately be picked up unless the cache is flushed.

**Comment by mxmilkiib** [comment]
Moving indicator-sound-switcher-symbolic.svg to indicator-sound-switcher-symbolic2.svg and trying to run gives this error icon;

![image](https://user-images.githubusercontent.com/108225/195718237-0eada6aa-79d5-4de1-ad95-8bfebae7d575.png)

**Comment by yktoo** [comment]
Okay, so the icon is picked up correctly. Which apparently means the SVG is rendered incorrectly by the system. To verify this you can swap it for another well-working SVG.

**Comment by mxmilkiib** [comment]
I used the qbt icon; the blue one in the tray is qbt itself, the dark circle is indicator-sound-switcher

![image](https://user-images.githubusercontent.com/108225/196064814-b6d00da3-de79-4f71-aefd-9ed9ca36b5ea.png)

**Comment by mxmilkiib** [comment]
I used the qbt icon; the blue one in the tray is qbt itself, the dark circle is indicator-sound-switcher

![image](https://user-images.githubusercontent.com/108225/196064814-b6d00da3-de79-4f71-aefd-9ed9ca36b5ea.png)

**Comment by mxmilkiib** [comment]
I used the qbt icon; the blue one in the tray is qbt itself, the dark circle is indicator-sound-switcher

![image](https://user-images.githubusercontent.com/108225/196064814-b6d00da3-de79-4f71-aefd-9ed9ca36b5ea.png)

**Comment by yktoo** [comment]
Did you also rename it to `*-symbolic`? Because otherwise it's just bizarre it's rendered this way.

**Comment by mxmilkiib** [comment]
Yes, the filename in the terminal is that opened image.

**Comment by yktoo** [comment]
Well it does look like your environment is unable to display symbolic icons properly; this might be caused though by some quirks in SSI's SVG file. I used SVGO to minimise the file, and that is sometimes known to cause issues.

You could try to replace the SSI's SVG with another symbolic icon (and not a regular one like you did), just to see if it's rendered as expected.

You can also try [this unoptimised icon](https://user-images.githubusercontent.com/1675911/196116782-0c32587c-b3b4-4f7d-9588-da2ffe2a79cb.svg).

**Comment by mxmilkiib** [comment]
Sorry, bit of PEBKAC there! Replaying symbolic with symbolic does make better sense..

I replaced the ISS icon with a symbolic icon rater with a general icon. After reboot, the tray shows a completly blank space (black on black) for ISS.

The graphic in the file is white, and it is shown as such in the dark GTK theme in the app it comes from.

**Comment by yktoo** [comment]
> The graphic in the file is white, and it is shown as such in the dark GTK theme in the app it comes from.

I'm not sure what you meant by that.

If another, valid, symbolic icon doesn't show up properly (that's what you meant with "shows a completly blank space"?) then it most probably means your system lacks proper support for such icons.

**Comment by mxmilkiib** [comment]
Can indicator-sound-switcher please be made to accommodate systems that can't handle symbolic icons in their tray/notification area?

**Comment by yktoo** [comment]
I wish I knew how to do that.

But can you confirm a non-symbolic icon is displayed correctly in the SSI?

**Comment by mxmilkiib** [comment]
for those still affected by this when they try;

I pointed Cursor at the app, and it turned the black on black icon into a red icon-missing icon, which is better than nothing

not gonna repost the change because its not a true fix, but eh it works enough for me now!

you can try replicate this yourself with free credit/models

(if you've not had your "oh shit" moment yet, AI IDEs are good if you give a good prompt, + using a good model, something that changes monthly)

if I have spare brain cycles and time in the future, I'll try for a complete fix/PR
